---
version: 2
jobs:
  build:
    working_directory: /opt/app/pdf_maker

    docker:
      - image: ciroque/alpine3.8:with-wkhtmltopdf

    environment:
      MIX_ENV: test
      DB_HOST: 127.0.0.1
      DB_USER: root
      DB_PASS: root
      PDF_MAKER_KEY_BASE: $PDF_MAKER_KEY_BASE

    steps:
      - checkout

      - run: cp mix.lock mix.lock.orig

      - restore_cache:
          keys:
            - pdf_maker-{{ checksum "mix.lock.orig" }}
            - pdf_maker-{{ .Branch }}
            - pdf_maker-master

      - run:
          name: Download dependencies
          command: mix deps.get

      - save_cache:
          key: pdf_maker-{{ .Branch }}
          paths:
            - _build
            - deps

      - save_cache:
          key: pdf_maker-{{ checksum "mix.lock.orig" }}
          paths:
            - _build
            - deps

      - run:
          name: Run Tests
          command: mix test

      ## Prod docker image building
      - restore_cache:
          keys:
            - pdf_maker-prod-{{ checksum "mix.lock.orig" }}
            - pdf_maker-prod-{{ .Branch }}
            - pdf_maker-prod-master

      - run:
          name: Compile for prod
          command: |
            MIX_ENV=prod mix release

      - save_cache:
          key: pdf_maker-prod-{{ .Branch }}
          paths:
            - _build/prod

      - save_cache:
          key: pdf_maker-prod-{{ checksum "mix.lock.orig" }}
          paths:
            - _build/prod

      - run:
          name: Allow _build to copy for docker building
          command: sed -i 's/_build//' .dockerignore

      # all steps after this run in the remote environment
      - type: setup-docker-engine
        reusable: true
        version: 17.05.0-ce

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.05.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Build docker image and publish image tagged with commit
          command: |
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
            docker build -t avvo/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 .
            docker push ciroque/pdf_maker:$CIRCLE_SHA1
workflows:
  version: 2
  build:
    jobs:
    - build:
        context: org-global